service: ${self:custom.prefix}-data-storage

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ${opt:region}
  stage: ${opt:stage}
  stackName: ${self:custom.prefix}-data-storage
  iam:
    role:
      name: ${self:custom.prefix}-data-storage-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'iam:DeleteBucket'
  deploymentBucket:
    name: perfect-projects-deployments

plugins:
  - serverless-deployment-bucket

custom:
  prefix: perfect-projects-${self:provider.stage}-${self:provider.region}

resources:
    Resources:
        perfectProjectsStorage:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: Private
            BucketName: ${self:custom.prefix}-storage
            LoggingConfiguration:
              LogFilePrefix: ${self:custom.prefix}
        perfectProjectsProjectTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.prefix}-projects
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: user_id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                GlobalSecondaryIndexes:
                  - IndexName: user_id
                    KeySchema:
                      - AttributeName: user_id
                        KeyType: HASH
                    Projection:
                      ProjectionType: "ALL"
                BillingMode: PAY_PER_REQUEST