service: perfect-projects-database

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: perfect-project-database-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'iam:DeleteBucket'
  deploymentBucket:
    name: perfect-project-database

plugins:
  - serverless-deployment-bucket

resources:
    Resources:
        ppShortDescription:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: project
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: user_id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                GlobalSecondaryIndexes:
                  - IndexName: user_id
                    KeySchema:
                      - AttributeName: user_id
                        KeyType: HASH
                    Projection:
                      ProjectionType: "ALL"
                BillingMode: PAY_PER_REQUEST