service: perfect-projects-data-storage

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: perfect-project-data-storage-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'iam:DeleteBucket'
  deploymentBucket:
    name: perfect-project-data-storage

plugins:
  - serverless-deployment-bucket

resources:
    Resources:
        perfetcProjectsStorage:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: Private
            BucketName: perfect-projects-s3-storage
            LoggingConfiguration:
              LogFilePrefix: perfect-projects
        perfectProjectsProjectTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: projects
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: user_id
                      AttributeType: S
                    - AttributeName: timestamp
                      AttributeType: N
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                    - AttributeName: timestamp
                      KeyType: RANGE
                GlobalSecondaryIndexes:
                  - IndexName: user_id
                    KeySchema:
                      - AttributeName: user_id
                        KeyType: HASH
                    Projection:
                      ProjectionType: "ALL"
                BillingMode: PAY_PER_REQUEST