name: deploy-eu-central-1-dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-eu-central-1-dev:
    runs-on: ubuntu-latest
    steps:
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install npm dependencies
        run: npm install
      - name: deploy
        run: npx serverless deploy --region eu-central-1 --stage dev
